# Action Mailer Setup --------------------------------------

# MAILER_PASSWORD: 'ENTER SMTP PASSWORD HERE'

# Secret Token ----------------------------------

# SECRET_TOKEN: 'GENERATE A RANDOM TOKEN'

# Carrier Wave Amazon S3 ------------------------------------------------

# S3_ACCESS_KEY: 'ENTER THE S3 ACCESS KEY'

# S3_SECRET_KEY: 'ENTER THE S3 SECRET KEY'